###  NumPy

In [1]:
import timeit
import numpy as np

size = 1000000

list1 = range(size)
list2 = range(size)
arr1 = np.arange(size)
arr2 = np.arange(size)

start = timeit.default_timer()
# multiply Python lists
result_list = [(a * b) for a, b in zip(list1, list2)]
print("Python time: ", timeit.default_timer() - start)

start = timeit.default_timer()
# multiply NumPy arrays
result_array = arr1 * arr2
print("NumPy Time: ", timeit.default_timer() - start)

Python time:  0.056146100017940626
NumPy Time:  0.0009941000025719404


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.shape

(2, 3)

In [4]:
re_arr = arr.reshape(3, 2)
re_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.zeros((2, 3))
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.empty((2, 3)) # doesn't initialize values

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
# evenly spaced numbers
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [9]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [10]:
np.multiply(arr1, arr2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [11]:
arr1.dot(arr2.T)

array([[ 50,  68],
       [122, 167]])

In [12]:
# inverse of a matrix
arr = np.array([[4, 3], [3, 2]])
inv_arr = np.linalg.inv(arr)
arr.dot(inv_arr)

array([[1., 0.],
       [0., 1.]])