###  NumPy

In [1]:
import timeit
import numpy as np

size = 1000000

list1 = range(size)
list2 = range(size)
arr1 = np.arange(size)
arr2 = np.arange(size)

start = timeit.default_timer()
# multiply Python lists
result_list = [(a * b) for a, b in zip(list1, list2)]
print("Python time: ", timeit.default_timer() - start)

start = timeit.default_timer()
# multiply NumPy arrays
result_array = arr1 * arr2
print("NumPy Time: ", timeit.default_timer() - start)

Python time:  0.07089810000616126
NumPy Time:  0.0009516999998595566


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.shape

(2, 3)

In [4]:
re_arr = arr.reshape(3, 2)
re_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.zeros((2, 3))
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.empty((2, 3)) # doesn't initialize values

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
# evenly spaced numbers
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [9]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [10]:
np.multiply(arr1, arr2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [11]:
arr1.dot(arr2.T)

array([[ 50,  68],
       [122, 167]])

In [12]:
# inverse of a matrix
arr = np.array([[4, 3], [3, 2]])
inv_arr = np.linalg.inv(arr)
arr.dot(inv_arr)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate((arr1, arr2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.hstack((arr1, arr2)) # horizontal stack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [17]:
np.random.randn(2, 3) # random numbers from a normal distribution

array([[ 0.36793322,  0.04712349, -0.61485077],
       [ 0.25941492,  0.9196201 ,  0.47494955]])

In [18]:
np.random.seed(11)
arr = np.random.randint(0, 10, size=(4, 6)) # [)
arr

array([[9, 0, 1, 7, 1, 7],
       [2, 8, 0, 0, 4, 2],
       [1, 5, 5, 7, 4, 1],
       [8, 8, 1, 3, 6, 2]])

In [19]:
arr[1][1]

8

In [20]:
arr[1] # row

array([2, 8, 0, 0, 4, 2])

In [21]:
arr[:, 1] # column

array([0, 8, 5, 8])

In [22]:
arr[[1, 2], :] # rows 1 and 2

array([[2, 8, 0, 0, 4, 2],
       [1, 5, 5, 7, 4, 1]])

In [23]:
arr[:, [1, 2]] # columns 1 and 2

array([[0, 1],
       [8, 0],
       [5, 5],
       [8, 1]])

In [24]:
arr[1:3, :] # row 1 to row 2

array([[2, 8, 0, 0, 4, 2],
       [1, 5, 5, 7, 4, 1]])

In [25]:
arr[[1, 2], :][:, [1, 2]] # rows 1 and 2, columns 1 and 2

array([[8, 0],
       [5, 5]])

In [26]:
arr[::-1] # reverse rows

array([[8, 8, 1, 3, 6, 2],
       [1, 5, 5, 7, 4, 1],
       [2, 8, 0, 0, 4, 2],
       [9, 0, 1, 7, 1, 7]])

In [27]:
arr[:, ::-1] # reverse columns

array([[7, 1, 7, 1, 0, 9],
       [2, 4, 0, 0, 8, 2],
       [1, 4, 7, 5, 5, 1],
       [2, 6, 3, 1, 8, 8]])

In [28]:
arr[::2] # rows with step 2

array([[9, 0, 1, 7, 1, 7],
       [1, 5, 5, 7, 4, 1]])

In [29]:
np.sum(arr, axis=0) # sum of columns, 1 for rows

array([20, 21,  7, 17, 15, 12])

In [30]:
np.sort(arr, axis=0) # sort columns, 1 for rows

array([[1, 0, 0, 0, 1, 1],
       [2, 5, 1, 3, 4, 2],
       [8, 8, 1, 7, 4, 2],
       [9, 8, 5, 7, 6, 7]])

In [31]:
np.sort(arr, axis=0)[::-1] # sort columns in descending order

array([[9, 8, 5, 7, 6, 7],
       [8, 8, 1, 7, 4, 2],
       [2, 5, 1, 3, 4, 2],
       [1, 0, 0, 0, 1, 1]])

In [32]:
arr[arr > 5]

array([9, 7, 7, 8, 7, 8, 8, 6])

In [33]:
arr = np.array([[11, 22, 33, 44, 55, 66]])
print(np.where(arr > 33)) # indices of elements > 33
print(np.where(arr > 33, 77, 88)) # replace elements > 33 with 77, else 88

(array([0, 0, 0], dtype=int64), array([3, 4, 5], dtype=int64))
[[88 88 88 77 77 77]]


In [34]:
np.all(arr > 33) # all elements > 33

False

In [35]:
np.any(arr > 33) # any element > 3

True